package com.opiumfive.telechart.chart.formatter;


import com.opiumfive.telechart.chart.model.AxisValue;

public interface AxisValueFormatter {
    public int formatValueForManualAxis(char[] formattedValue, AxisValue axisValue);
    public int formatValueForAutoGeneratedAxis(char[] formattedValue, float value, int autoDecimalDigits);
}
